excluded:
- Pods

disabled_rules:
- todo

opt_in_rules:
- array_init
- attributes
- closure_end_indentation
- closure_spacing
- contains_over_first_not_nil
- empty_count
- empty_string
- empty_xctest_method
- explicit_init
- fatal_error_message
- file_name
- first_where
- force_unwrapping
- function_default_parameter_at_end
- implicit_return
- joined_default_parameter
- modifier_order
- object_literal
- number_separator
- operator_usage_whitespace
- overridden_super_call
- pattern_matching_keywords
- private_action
- prohibited_super_call
- redundant_nil_coalescing
- sorted_first_last
- sorted_imports
- trailing_closure
- unneeded_parentheses_in_closure_argument
- vertical_parameter_alignment_on_call
- yoda_condition
- reduce_into
# - type_contents_order

trailing_closure:
  only_single_muted_parameter: true

line_length: 140
